language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - tcl-vtk

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
#before_script: ./develop/get_test_data_all.bash
#before_script:
  - Xvfb :1 -screen 0 1280x1024x24 -auth localhost &
  - export DISPLAY=:1

script: pytest
