language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
#before_script: ./develop/get_test_data_all.bash

script: pytest
