{% set name = "brainview" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eebbea1eb6beaa41e5ddda9a46e1a216255b12000d37e4e41f0ca65400515483

build:
  number: 0
  entry_points:
    - brainviewer = brainview.brainviewer:brainviewer
    - atlasviewer = brainview.atlasviewer:atlasviewer
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - brainload >=0.3.2
    - matplotlib
    - mayavi
    - nibabel
    - numpy
    - pip
    - python
    - vtk
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-console-scripts
    - bz2file
  run:
    - brainload >=0.3.2
    - nibabel
    - numpy
    - pytest
    - pytest-cov
    - pytest-runner
    - pytest-console-scripts
    - bz2file

test:
  imports:
    - brainview
  commands:
    - brainviewer --help
    - atlasviewer --help
  requires:
    - pytest
    - pytest-console-scripts
    - pytest-cov
    - pytest-runner

about:
  home: https://github.com/dfsp-spirit/brainview
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Visualize morphometry neuroimaging data on three-dimensional brain surface meshes.
  doc_url: http://dfsp-spirit.github.io/brainview
  dev_url: https://github.com/dfsp-spirit/brainview
  description: |
    Visualize surface-based brain morphometry data like cortical thickness on
    brain surface meshes. The meshes can be loaded from FreeSurfer file formats,
    and the data can be anything. The result is an interactive visualization
    based on matplotlib and mayavi. While the result can be saved to an image file,
    this module does not try to produce publication-ready plots but focuses on
    interactive visualization.


extra:
  recipe-maintainers:
    - dfsp-spirit
